import groovy.json.JsonSlurperClassic

def jsonParse(def json) {
    new JsonSlurperClassic().parseText(json)
}
pipeline {
    agent { label 'master' }
    environment {
        appName = 'variable'
    }
    stages {
        stage('paso 1') {
            steps {
                script {
                    sh "echo 'hola mundo'"
                }
            }
        }
        stage('run-parallel-branches') {
            steps {
                parallel(
                    a: {
                        echo 'This is branch a'
                    },
                    b: {
                        echo 'This is branch b'
                    }
                )
            }
        }
    }
    post {
        always {
            deleteDir()
            sh "echo 'fase always'"
        }
        success {
            sh "echo 'fase success'"
        }
        failure {
            sh "echo 'fase failure'"
        }
    }
}
